=begin
#Schematic API

#Schematic API

The version of the OpenAPI document: 0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Schematic::CheckFlagRequestBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Schematic::CheckFlagRequestBody do
  let(:instance) { Schematic::CheckFlagRequestBody.new }

  describe 'test an instance of CheckFlagRequestBody' do
    it 'should create an instance of CheckFlagRequestBody' do
      expect(instance).to be_instance_of(Schematic::CheckFlagRequestBody)
    end
  end
  describe 'test attribute "company"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "user"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
