=begin
#Schematic API

#Schematic API

The version of the OpenAPI document: 0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Schematic::EventBodyIdentifyCompany
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Schematic::EventBodyIdentifyCompany do
  let(:instance) { Schematic::EventBodyIdentifyCompany.new }

  describe 'test an instance of EventBodyIdentifyCompany' do
    it 'should create an instance of EventBodyIdentifyCompany' do
      expect(instance).to be_instance_of(Schematic::EventBodyIdentifyCompany)
    end
  end
  describe 'test attribute "keys"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "traits"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
