=begin
#Schematic API

#Schematic API

The version of the OpenAPI document: 0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Schematic::SyncCompanyPlansRequestBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Schematic::SyncCompanyPlansRequestBody do
  let(:instance) { Schematic::SyncCompanyPlansRequestBody.new }

  describe 'test an instance of SyncCompanyPlansRequestBody' do
    it 'should create an instance of SyncCompanyPlansRequestBody' do
      expect(instance).to be_instance_of(Schematic::SyncCompanyPlansRequestBody)
    end
  end
  describe 'test attribute "company_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "plan_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "plans"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
