=begin
#Schematic API

#Schematic API

The version of the OpenAPI document: 0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Schematic::SyncCompanyPlansResponseData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Schematic::SyncCompanyPlansResponseData do
  let(:instance) { Schematic::SyncCompanyPlansResponseData.new }

  describe 'test an instance of SyncCompanyPlansResponseData' do
    it 'should create an instance of SyncCompanyPlansResponseData' do
      expect(instance).to be_instance_of(Schematic::SyncCompanyPlansResponseData)
    end
  end
  describe 'test attribute "plans"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
