=begin
#Schematic API

#Schematic API

The version of the OpenAPI document: 0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Schematic::UpdateEntityTraitDefinitionRequestBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Schematic::UpdateEntityTraitDefinitionRequestBody do
  let(:instance) { Schematic::UpdateEntityTraitDefinitionRequestBody.new }

  describe 'test an instance of UpdateEntityTraitDefinitionRequestBody' do
    it 'should create an instance of UpdateEntityTraitDefinitionRequestBody' do
      expect(instance).to be_instance_of(Schematic::UpdateEntityTraitDefinitionRequestBody)
    end
  end
  describe 'test attribute "skip_webhooks"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "trait_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
